### ISSUE TITLE
checkNegativeCache panics if there are no resolver records

### ISSUE THREAD

**Issue by devdua** [jvns/dns-doctor#2]
The `negative-check` fails if there are no resolver records for the domain being checked. The `no-record` check runs fine.
```
dns-doctor d.idua.dev
FAILURE: no-record
  Details: No record found, using nameserver '162.159.8.140'
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.checkNegativeCache(0x1400007e630?, 0x14000164000?)
	/Users/dev/go/pkg/mod/github.com/jvns/dns-doctor@v0.0.0-20230901221835-966027c368b6/check_negative_cache.go:29 +0x294
main.runCheck(0x10125f6e0, 0x7?, 0x14000016570?)
	/Users/dev/go/pkg/mod/github.com/jvns/dns-doctor@v0.0.0-20230901221835-966027c368b6/checks.go:21 +0x34
main.doctor(0x1400007e630)
	/Users/dev/go/pkg/mod/github.com/jvns/dns-doctor@v0.0.0-20230901221835-966027c368b6/main.go:77 +0x3ac
main.main.func1(0x14000122300?, {0x140000221d0, 0x1, 0x10105c9b5?})
	/Users/dev/go/pkg/mod/github.com/jvns/dns-doctor@v0.0.0-20230901221835-966027c368b6/main.go:49 +0xf4
github.com/spf13/cobra.(*Command).execute(0x14000014600, {0x14000012050, 0x1, 0x1})
	/Users/dev/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x14000014600)
	/Users/dev/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/dev/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/Users/dev/go/pkg/mod/github.com/jvns/dns-doctor@v0.0.0-20230901221835-966027c368b6/main.go:52 +0x54
```

Confirmed by rebuilding the binary with a print of the response (`outputs.resolverNoRecurse.Answers`):
```
./dns-doctor d.idua.dev
FAILURE: no-record
  Details: No record found, using nameserver '173.245.58.37'
RESOLVER_RECORDS = []
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.checkNegativeCache(0x1400007e630?, 0x14000164000?)
	/Users/dev/interesting/dns-doctor/check_negative_cache.go:29 +0x318
main.runCheck(0x104de3720, 0x7?, 0x14000016558?)
	/Users/dev/interesting/dns-doctor/checks.go:21 +0x34
main.doctor(0x1400007e630)
	/Users/dev/interesting/dns-doctor/main.go:77 +0x3ac
main.main.func1(0x14000122300?, {0x140000221d0, 0x1, 0x104be0a35?})
	/Users/dev/interesting/dns-doctor/main.go:49 +0xf4
github.com/spf13/cobra.(*Command).execute(0x14000014600, {0x14000012050, 0x1, 0x1})
	/Users/dev/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x14000014600)
	/Users/dev/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/dev/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/Users/dev/interesting/dns-doctor/main.go:52 +0x54
```

**Comment by jvns** [comment]
Can you share the output of `dig` that `dns-doctor` saved in `/tmp/dns-doctor-logs/`? That would make it easier to figure out what the right resolution is and add a test.

**Comment by devdua** [comment]
```
$ cat /tmp/dns-doctor-logs/d.idua.dev_A_norecurse.dig

; <<>> DiG 9.10.6 <<>> +all +norecurse A d.idua.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12903
;; flags: qr ra; QUERY: 1, ANSWER: 0, AUTHORITY: 13, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;d.idua.dev.			IN	A

;; AUTHORITY SECTION:
.			3600000	IN	NS	M.ROOT-SERVERS.NET.
.			3600000	IN	NS	J.ROOT-SERVERS.NET.
.			3600000	IN	NS	H.ROOT-SERVERS.NET.
.			3600000	IN	NS	D.ROOT-SERVERS.NET.
.			3600000	IN	NS	G.ROOT-SERVERS.NET.
.			3600000	IN	NS	B.ROOT-SERVERS.NET.
.			3600000	IN	NS	I.ROOT-SERVERS.NET.
.			3600000	IN	NS	F.ROOT-SERVERS.NET.
.			3600000	IN	NS	E.ROOT-SERVERS.NET.
.			3600000	IN	NS	C.ROOT-SERVERS.NET.
.			3600000	IN	NS	A.ROOT-SERVERS.NET.
.			3600000	IN	NS	L.ROOT-SERVERS.NET.
.			3600000	IN	NS	K.ROOT-SERVERS.NET.

;; Query time: 149 msec
;; SERVER: 100.100.100.100#53(100.100.100.100)
;; WHEN: Wed Sep 13 08:51:11 IST 2023
;; MSG SIZE  rcvd: 262

$ cat /tmp/dns-doctor-logs/d.idua.dev_A_trace.dig

; <<>> DiG 9.10.6 <<>> +trace +all A d.idua.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32059
;; flags: qr ra; QUERY: 1, ANSWER: 0, AUTHORITY: 13, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
;; QUESTION SECTION:
;.				IN	NS

;; AUTHORITY SECTION:
.			3600000	IN	NS	F.ROOT-SERVERS.NET.
.			3600000	IN	NS	M.ROOT-SERVERS.NET.
.			3600000	IN	NS	I.ROOT-SERVERS.NET.
.			3600000	IN	NS	G.ROOT-SERVERS.NET.
.			3600000	IN	NS	J.ROOT-SERVERS.NET.
.			3600000	IN	NS	C.ROOT-SERVERS.NET.
.			3600000	IN	NS	D.ROOT-SERVERS.NET.
.			3600000	IN	NS	B.ROOT-SERVERS.NET.
.			3600000	IN	NS	L.ROOT-SERVERS.NET.
.			3600000	IN	NS	H.ROOT-SERVERS.NET.
.			3600000	IN	NS	E.ROOT-SERVERS.NET.
.			3600000	IN	NS	K.ROOT-SERVERS.NET.
.			3600000	IN	NS	A.ROOT-SERVERS.NET.

;; Query time: 144 msec
;; SERVER: 100.100.100.100#53(100.100.100.100)
;; WHEN: Wed Sep 13 08:51:05 IST 2023
;; MSG SIZE  rcvd: 251

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30129
;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 7, ADDITIONAL: 11

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1472
;; QUESTION SECTION:
;d.idua.dev.			IN	A

;; AUTHORITY SECTION:
dev.			172800	IN	NS	ns-tld1.charlestonroadregistry.com.
dev.			172800	IN	NS	ns-tld2.charlestonroadregistry.com.
dev.			172800	IN	NS	ns-tld3.charlestonroadregistry.com.
dev.			172800	IN	NS	ns-tld4.charlestonroadregistry.com.
dev.			172800	IN	NS	ns-tld5.charlestonroadregistry.com.
dev.			86400	IN	DS	60074 8 2 B942E2CE5AEBF62FCA59D05707E6DBB795211D540D8ADBA02E9E89E8 33424785
dev.			86400	IN	RRSIG	DS 8 1 86400 20230925190000 20230912180000 11019 . Sfe3phDptsCd9SLEo/QhdC8qMxKe6p+vIxSDgRUl50r3IN/avgAb5BVD R6GtbrBYKYCJfwcyu4jBRMNiINLVyPulrnsx5+N8umiZiiFMywWcmxcT 2dATVqRsKpfWxUggAVUEw7h3x6BngXrQyJrpwSJwnWBSTg+N7OpCXLMN uiH6+7OPhYu3j0YBEJmn9qhbCrm/GxHnQ1ze6jVPuKrBm/8cbps6RdMs 6PNBfj2gbdMoEnLb3NZ+nCizu5eb8rADG7z+b74ms+Zjb6oKxpQX4ePL c76HG5qEklqU7l2K8rqMzGwQbyrhYc1Xus4mFu584GYEzPZa1R325AdP 8yPTGg==

;; ADDITIONAL SECTION:
ns-tld1.charlestonroadregistry.com. 172800 IN A	216.239.32.105
ns-tld1.charlestonroadregistry.com. 172800 IN AAAA 2001:4860:4802:32::69
ns-tld2.charlestonroadregistry.com. 172800 IN A	216.239.34.105
ns-tld2.charlestonroadregistry.com. 172800 IN AAAA 2001:4860:4802:34::69
ns-tld3.charlestonroadregistry.com. 172800 IN A	216.239.36.105
ns-tld3.charlestonroadregistry.com. 172800 IN AAAA 2001:4860:4802:36::69
ns-tld4.charlestonroadregistry.com. 172800 IN A	216.239.38.105
ns-tld4.charlestonroadregistry.com. 172800 IN AAAA 2001:4860:4802:38::69
ns-tld5.charlestonroadregistry.com. 172800 IN A	216.239.60.105
ns-tld5.charlestonroadregistry.com. 172800 IN AAAA 2001:4860:4805::69

;; Query time: 28 msec
;; SERVER: 192.203.230.10#53(192.203.230.10)
;; WHEN: Wed Sep 13 08:51:06 IST 2023
;; MSG SIZE  rcvd: 730

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35545
;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 6, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 512
;; QUESTION SECTION:
;d.idua.dev.			IN	A

;; AUTHORITY SECTION:
idua.dev.		10800	IN	NS	curitiba.ns.porkbun.com.
idua.dev.		10800	IN	NS	maceio.ns.porkbun.com.
idua.dev.		10800	IN	NS	salvador.ns.porkbun.com.
idua.dev.		10800	IN	NS	fortaleza.ns.porkbun.com.
idua.dev.		3600	IN	DS	63080 8 2 3D82A245DE6657326BE0A401124EBD75E4FEE552B8FF47424CF2EA9D EFC63DCB
idua.dev.		3600	IN	RRSIG	DS 8 2 3600 20231003103310 20230911103310 10245 dev. KT8GE3Z6+TkpqmsxGht9MFZO56BiTxgc4WWGJVaJ8Rmb4C/j2yV6mCeq Xh7XIMS5EdVni7UbI9ZrhF58TSSUK95IzneS6ar68svJT80dNvXy4q9w PZ7IpW4zNzTQDht/WjPPYxmbk2vqRId0SvtR9XX2TyXSe8va/yDHizGE UbQ=

;; Query time: 252 msec
;; SERVER: 216.239.60.105#53(216.239.60.105)
;; WHEN: Wed Sep 13 08:51:09 IST 2023
;; MSG SIZE  rcvd: 355

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 65171
;; flags: qr aa; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
;; QUESTION SECTION:
;d.idua.dev.			IN	A

;; AUTHORITY SECTION:
idua.dev.		1800	IN	SOA	curitiba.ns.porkbun.com. dns.cloudflare.com. 2316783415 10000 2400 604800 1800

;; Query time: 23 msec
;; SERVER: 162.159.8.140#53(162.159.8.140)
;; WHEN: Wed Sep 13 08:51:11 IST 2023
;; MSG SIZE  rcvd: 113

```
